name =input("please enter your name:")
print(name)
age =input("what is your age?")
print(age)
city =input("In which city do you live")
print(city)
print("we want to know if you like programming")
print()
print("Do you like programming"+name+"?")
answer= input()
print("Great! you said" +answer+"?")
print("let's learn some python today")

input("press to exit")
